import os
import shutil
import re

source_dir = r"C:\Users\ELCOT\.gemini\antigravity\brain\303fc210-f962-4d79-a335-83141a71a9fb"
dest_dir = r"d:\groww\massage\images"

if not os.path.exists(dest_dir):
    os.makedirs(dest_dir)

# Mapping of original sources to local filenames
mappings = {
    "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80": "spa_experience.png",
    "https://images.unsplash.com/photo-1519823551278-64ac92734fb1?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80": "relaxing_ambiance.png",
    "https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80": "therapy_session.png",
    "https://randomuser.me/api/portraits/women/44.jpg": "sarah_j.png",
    "https://randomuser.me/api/portraits/men/32.jpg": "michael_t.png",
    "https://randomuser.me/api/portraits/women/68.jpg": "emma_l.png",
    "https://randomuser.me/api/portraits/men/46.jpg": "david_m.png",
    "https://images.unsplash.com/photo-1600334129128-685c5582fd35?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80": "mobile_setup.png"
}

# Image files generated by Gemini
generated_images = {
    "spa_experience": "spa_experience_1781254361398.png",
    "relaxing_ambiance": "relaxing_ambiance_1781254373761.png",
    "therapy_session": "therapy_session_1781254386668.png",
    "sarah_j": "sarah_j_1781254396820.png",
    "michael_t": "michael_t_1781254407877.png",
    "emma_l": "emma_l_1781254420459.png",
    "david_m": "david_m_1781254433443.png",
    "about_img": "about_img_1781254447162.png",
    "service_one": "service_one_1781254459529.png",
    "mobile_massage": "mobile_massage_1781254474945.png",
    "service_two": "service_two_1781254487215.png",
    "hero_bg": "hero_bg_1781254500948.png",
    "mobile_setup": "mobile_setup_1781254512708.png"
}

# Copy images
for name, filename in generated_images.items():
    src = os.path.join(source_dir, filename)
    dst = os.path.join(dest_dir, f"{name}.png")
    if os.path.exists(src):
        shutil.copy2(src, dst)
        print(f"Copied {filename} to {name}.png")
    else:
        print(f"Warning: {src} not found")

# Update HTML files
html_dir = r"d:\groww\massage"
for filename in os.listdir(html_dir):
    if filename.endswith(".html"):
        filepath = os.path.join(html_dir, filename)
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()
        
        updated = False
        for old_url, new_img in mappings.items():
            if old_url in content:
                content = content.replace(old_url, f"images/{new_img}")
                updated = True
        
        # Also let's check for any other random url that might be missed but starts with http in img src
        # Because we only listed the ones we found earlier.
        
        if updated:
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(content)
            print(f"Updated {filename}")
